export const productos = [
{id: 1,
    nombre: "alfajor",
    precio: 100,
    stock: true},
{id: 2,
    nombre: "trufas",
    precio: 80,
    stock: true},
{id: 3,
    nombre: "galletitas",
    precio: 90,
    stock: true,},
{id: 4,
    nombre: "gaseosa sin azucar",
    precio: 100,
    stock: true,},
{id: 5,
    nombre: "exprimidos naturales",
    precio: 150,
    stock: true,},
{id: 6,
    nombre: "1/2kg de chipas",
    precio: 200,
    stock: true,},
{id: 7,
    nombre: "ensalada de frutas",
    precio: 110,
    stock: true,},
    ]

